"""
Django settings for backend project.

Logging configuration added for proper debug output.
"""
import logging

# Configure logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'tplanet': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

"""

Generated by 'django-admin startproject' using Django 2.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
import datetime
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '2ulidgoo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',

    # Custom apps
    'accounts',
    'projects',
    'portal',
    'weight',
    'dashboard',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS_ALLOW_ALL_ORIGINS = True
"""
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://beta-tplanet-backend.4impact.cc",
]
"""

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://localhost(:\d+)?$",         
    r"^https://.*\.4impact\.cc$", 
    r"^https://.*\..*\.4impact\.cc$",
    r"^https://.*\.sechome\.cc$",
    r"^https://4impact\.cc$",
    r"^https://.*\.postman\.co$",
    r"^https://beta-cms\.ntsdgs\.tw$",
    r"^https://cms\.ntsdgs\.tw$",
    r"^https://ntidipc\.ntsdgs\.tw$",
]

CORS_ALLOW_CREDENTIALS = True

# CORS allowed methods and headers (handled by middleware)
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-tenant-id",
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'tplanet',
        'USER': 'postgres',
        'PASSWORD': '2ulidgoo',
        'HOST': 'tplanet-db-beta',
        'PORT': 5432,
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

USE_TZ = True
TIME_ZONE = "Asia/Taipei" 

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = []


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': datetime.timedelta(minutes = 300),
}

# Google oauth
SOCIAL_GOOGLE_CLIENT_ID = '17954716006-6rgerjnebjbek1p7u9om572icrm2d4ih.apps.googleusercontent.com'

# Facebook oauth
FACEBOOK_EID_ACESS_TOKEN = '597308661353623|d78hExtJE6WOD0SUi4YLH53CICg'
FACEBOOK_DEBUG_TOKEN_URL = 'https://graph.facebook.com/v12.0/debug_token'

# TPlanet
URL_TPLANET = "https://beta-tplanet-backend.townway.com.tw"

# Project resource URL list
URL_PROJECT_RESOURCE = ["http://127.0.0.1", "http://localhost", "https://5684d6c0-ae89-48d0-8ca7-2aef25d76836.mock.pstmn.io"]

# Avatar URL/PATH
URL_DEFAULT_AVATAR_IMG_FILE = "/static/imgs/pages/user.png"
URL_AVATAR_IMG = "/static/avatar/imgs/"
PATH_AVATAR_IMG = "backend/static/avatar/imgs/"

# NFT
NFT_API_ENDPOINT = "https://beta-nft.townway.com.tw"
URL_OPENSEA = "https://testnets.opensea.io/assets/mumbai/0x63818f1dd00287d70a9e8e976618471a3659d30a/"

# OpenAI
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")

# SROI
FILE_ID_OF_SDG_SROI_MAPPING = "1MJqwHArEf89PtOW8dJ3N1ar25JEbAjnEcb3A857eusU"

# GMail
GMAIL_USERNAME = "yillkid@gmail.com"
GMAIL_PASSWORD = "ojfw kuxt ggxu ujek"

# LLMTwins
URL_API_LLMTWIN = "https://beta-llmtwins.4impact.cc"

# DeepL Translation API
DEEPL_API_KEY = "4999b103-9401-45e5-a959-da505d5ea513:fx"
DEEPL_API_URL = "https://api-free.deepl.com/v2/translate"

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'EXCEPTION_HANDLER': 'utils.drf_exception_handler.custom_exception_handler',
}
